# This section tells Netlify where your serverless functions are located.
[functions]
  directory = "netlify/functions/"

# This schedules your 'updateDailyReviews' function to run automatically.
# The cron expression "0 6 * * *" means it will run at 06:00 UTC every day.
[functions.updateDailyReviews]
  schedule = "0 6 * * *"